### ISSUE TITLE
When I run 'git merge new-feature' I get a prompt asking me to add a message to the merge and placing me in some kind of text editor.

### ISSUE THREAD

**Issue by eskayio** [learn-co-curriculum/git-collaboration-readme#14]
Had to replace 'git merge new-feature' with 'git merge new-feature -m "Added new feature"' to get it to merge.

**Comment by PeterBell** [comment]
Hey @eskayio thanks so much for catching this - there is an error in the instructions. It suggests you'll get a fast-forward merge, but it's going to be a recursive merge which is going to create a merge commit to bring a copy of the work you did on the feature branch into master and it puts you into your default test editor - usually vi. You can use the -m option or you can hit "i" to go into insert mode in vi, then type in your commit message for the merge commit, then hit "esc" and then ":x" to save and quit out of vi which will then complete the recursive merge. Apologies - this lab needs some work - will mention it to @AnnJohn and @jmburges and will try to get this fixed up next week!

**Comment by aturkewi** [comment]
@PeterBell I just heard that this is still an issue. are you still taking a look at re-doing some of the git curriculum? Or should we just update the instructions to explain what students see here?

**Comment by PeterBell** [comment]
Ugh - realistically could you just update the instructions? The Git curriculum work is on a back burner right now :(

**Comment by PeterBell** [comment]
@aturkewi ^^
