### ISSUE TITLE
The "Merging Branches with Git Merge" section needs to be updated.

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/git-collaboration-readme#28]
The "Merging Branches with Git Merge" section is somewhat confusing because it instructs students to "tell git to use the Atom editor".

This may be good information for students who are following along with the lesson and are not using an Atom text environment. However, telling git to use the Atom editor is unnecessary when using the Learn IDE, because Learn ALREADY uses Atom.

Adding a couple of sentences about this would help prevent confusion for students who are coding along in the Learn IDE.

Thank you for looking into this!

Sdcrouse

**Comment by sgharms** [comment]
Helpful feedback! Fixed!
