### ISSUE TITLE
Is the git merge command formatted incorrectly in this README?   

### ISSUE THREAD

**Issue by SwellPF** [learn-co-curriculum/git-collaboration-readme#30]
I was going through this exercise and following along in the sandbox and everything was going great until I reached the point where I was supposed to merge my new branch back to the master.   The first problem was that it balked at the remote command not having been issued.  (It doesn't look like the walkthrough includes a mention of that so I hadn't done that. But I digress.)  But shouldn't the format of the merge command listed in the snippet below include the name of the branch you want to merge?   (I'm including the preceding paragraphs for context and bolded the line in question for emphasis):

> When we merge a branch with git merge, it's important to be currently working on your target branch, the branch you want to move into. The first step for our new-feature merge is to checkout master because that is where we want the commits to end up.
> 
> mission-critical-application $ git checkout master
> Switched to branch 'master'
> We're about to perform a merge, but we need to do one tiny bit of house-keeping.
> 
> For Users on the Learn In-Browser IDE
> Execute: **git merge -m "Adds new-feature because it is really great"**
> 
> This tells git to perform a merge of the new-feature branch with a message that is specified after the -m "flag." This "merge message" usually contains information about what the branch did and why its contents are desirable to have in the gaining branch. Let's try it out!

Thanks, Paul Fell

**Comment by drakeltheryuujin** [comment]
Hi @SwellPF,

It appears that the README is not complete. It asks the student to create a sample repository, and emphasizes creating and merging branches on a local repository that does not exist remotely. Commands like `git fetch`, and `git pull` on your local machine assume that you are working off of a repository that is connected to a remote (which it would be if it were cloned). Thank you for pointing out this issue. The README is has been rewritten for clarity and consistency, and should resolve the confusion. 

Thank you for your contribution 💙
